apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: TwoApi
namespace: production
bases:
  - ../../base
commonAnnotations:
  app: TwoApi
  backstage.io/kubernetes-id: "TwoApi"
commonLabels:
  app: TwoApi
  backstage.io/kubernetes-id: "TwoApi"
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml